[theme]
theme = "native"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
[block.format]
full = "    $title.str(max_w:55,rot_interval:0.2)  |"
short = "    $title.str(max_w:55,rot_interval:0.2)  |"


[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
format = "$icon {$average$max}"

[[block]]
block = "memory"
format = "$icon $mem_used_percents"
format_alt = "$icon_swap $swap_used_percents"

[[block]]
block = "net"
format = "$icon {$signal_strength.bar(width:1)|}$speed_up.eng(width:3,prefix:K,hide_unit:true) $speed_down.eng(width:3,prefix:K,hide_unit:true)"
format_alt = "$speed_up.eng(width:0,prefix:K,hide_unit:true) $speed_down.eng(width:0,prefix:K,hide_unit:true)"

# [[block]]
# block = "battery"
# device = "DisplayDevice"
# driver = "upower"
# full_format = ""
# missing_format = ""

[[block]]
block = "time"
interval = 1
format = "  $timestamp.datetime(f:'%V')"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%A %e %B')"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%r')"

[[block]]
block = "sound"
device_kind = "source"
format = "$icon"
[[block.click]]
button = "left"
cmd = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"

[[block]]
block = "sound"
headphones_indicator = true
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "notify"
if_command = "dunstctl is-paused"
